-- Create giveaway_entries table
-- Users can enter the giveaway by providing at least one social handle (Instagram or TikTok)
-- One entry per user, enforced by UNIQUE constraint on user_id

CREATE TABLE public.giveaway_entries (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          text NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  instagram_handle text,
  tiktok_handle    text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT at_least_one_handle CHECK (
    instagram_handle IS NOT NULL OR tiktok_handle IS NOT NULL
  )
);

-- Enable Row Level Security
ALTER TABLE public.giveaway_entries ENABLE ROW LEVEL SECURITY;

-- Users can insert their own entry only
CREATE POLICY "giveaway_entries_insert_own"
  ON public.giveaway_entries
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = (SELECT id FROM public.users WHERE id = auth.uid()::text LIMIT 1));

-- Users can read their own entry (to check if already entered)
CREATE POLICY "giveaway_entries_select_own"
  ON public.giveaway_entries
  FOR SELECT
  TO authenticated
  USING (user_id = (SELECT id FROM public.users WHERE id = auth.uid()::text LIMIT 1));
